# Used only for Debian/Ubuntu installation, as the -t option for apt.
  nginx_default_release: ""

# Use the official Nginx PPA for Ubuntu, and the version to use if so.
  nginx_ppa_use: false
  nginx_ppa_version: stable

# The name of the nginx package to install.
  nginx_package_name: "nginx"

  nginx_worker_processes: "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
  nginx_worker_connections: "1024"
  nginx_multi_accept: "off"

  nginx_error_log: "/var/log/nginx/error.log warn"
  nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"

  nginx_sendfile: "on"
  nginx_tcp_nopush: "on"
  nginx_tcp_nodelay: "on"

  nginx_keepalive_timeout: "65"
  nginx_keepalive_requests: "100"

  nginx_server_tokens: "on"

  nginx_client_max_body_size: "64m"

  nginx_server_names_hash_bucket_size: "64"

  nginx_proxy_cache_path: ""
